import { NewsArticle, NewsTag, AdBanner } from '@/types/news';

export const mockNews: NewsArticle[] = [
  {
    id: '1',
    title: 'Прорыв в искусственном интеллекте: новая модель превзошла все ожидания',
    summary: 'Исследователи представили революционную AI-модель, которая демонстрирует беспрецедентные возможности...',
    url: 'https://example.com/ai-breakthrough',
    source: 'TechNews',
    category: 'Технологии',
    publishedAt: new Date('2024-12-15T10:30:00'),
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop',
    views: 15420,
    trending: true,
  },
  {
    id: '2',
    title: 'Экономические новости: рост валютного рынка продолжается',
    summary: 'Аналитики отмечают стабильный рост основных валютных пар на фоне положительных экономических показателей...',
    url: 'https://example.com/economy-growth',
    source: 'BusinessDaily',
    category: 'Экономика',
    publishedAt: new Date('2024-12-15T09:15:00'),
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=250&fit=crop',
    views: 8940,
    trending: false,
  },
  {
    id: '3',
    title: 'Спорт: неожиданная победа в чемпионате мира',
    summary: 'Сборная продемонстрировала блестящую игру и одержала убедительную победу над фаворитами турнира...',
    url: 'https://example.com/sports-victory',
    source: 'SportsTimes',
    category: 'Спорт',
    publishedAt: new Date('2024-12-15T08:45:00'),
    imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=250&fit=crop',
    views: 12350,
    trending: true,
  },
  {
    id: '4',
    title: 'Научное открытие: найден новый способ лечения редких заболеваний',
    summary: 'Международная группа ученых разработала инновационный метод терапии, который может спасти тысячи жизней...',
    url: 'https://example.com/medical-breakthrough',
    source: 'MedicalJournal',
    category: 'Наука',
    publishedAt: new Date('2024-12-15T07:20:00'),
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=250&fit=crop',
    views: 6780,
    trending: false,
  },
  {
    id: '5',
    title: 'Политические новости: важные решения приняты на международном саммите',
    summary: 'Лидеры ведущих стран договорились о новых мерах по борьбе с глобальными вызовами...',
    url: 'https://example.com/political-summit',
    source: 'WorldNews',
    category: 'Политика',
    publishedAt: new Date('2024-12-15T06:00:00'),
    imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400&h=250&fit=crop',
    views: 18920,
    trending: true,
  },
  {
    id: '6',
    title: 'Культура: премьера нового фильма собрала рекордную аудиторию',
    summary: 'Долгожданная премьера стала настоящим событием в мире кино и побила все рекорды посещаемости...',
    url: 'https://example.com/movie-premiere',
    source: 'CultureToday',
    category: 'Культура',
    publishedAt: new Date('2024-12-14T20:30:00'),
    imageUrl: 'https://images.unsplash.com/photo-1489599904632-8421b814c171?w=400&h=250&fit=crop',
    views: 9640,
    trending: false,
  },
];

export const mockTags: NewsTag[] = [
  { id: '1', name: 'Технологии', color: '#3b82f6', count: 245 },
  { id: '2', name: 'Политика', color: '#ef4444', count: 189 },
  { id: '3', name: 'Экономика', color: '#10b981', count: 156 },
  { id: '4', name: 'Спорт', color: '#f59e0b', count: 134 },
  { id: '5', name: 'Наука', color: '#8b5cf6', count: 98 },
  { id: '6', name: 'Культура', color: '#ec4899', count: 87 },
  { id: '7', name: 'Общество', color: '#06b6d4', count: 76 },
  { id: '8', name: 'Здоровье', color: '#84cc16', count: 65 },
];

export const mockBanners: AdBanner[] = [
  {
    id: '1',
    title: 'Рекламный блок 1',
    content: 'Ваша реклама может быть здесь',
    position: 'top',
    active: true,
    priority: 1,
  },
  {
    id: '2',
    title: 'Баннер в sidebar',
    content: 'Размещение рекламы в боковой панели',
    position: 'sidebar',
    active: true,
    priority: 2,
  },
];